### ISSUE TITLE
`i_` and `a_` can be improved

### ISSUE THREAD

**Issue by kikyous** [kurkale6ka/vim-pairs#3]
`one_two_three`

`a_` only match `_two_`

but i think it's useful to have a text_objects to match both `one_`,`_two_`and`_three`

e.g.
`on[]e_two_three`
`ci_`    become  `_two_three`
`ca_`   become `two_three`

and aliases like `iu`,and `au` is convenient to type.

**Comment by kurkale6ka** [comment]
Hi,

I am trying to keep it as close as possible to Vim's core behaviour.
In Vim if you have the following: `on[]e"two"three` and you type `ci"`, it will insert inside the quotes.

Regards
